### ISSUE TITLE
III stage

### ISSUE THREAD

**Issue by rusdevops** [Niyaz97/TwitterClient#2]
@Niyaz97 

- [x] 1. Присутствует дублирование кода. [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L16-L24) и [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L16-L24).
- [x] 2. Отсутствует проверка корректного состояния стандартного потока ввода.
[здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L15), [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L20) и [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L30).
- [x] 3. Некорректное именование локальной переменной.
[здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L22).
- [x] 4. Отсутствует проверка возвращаемого значения.
[здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L6), [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L23) и [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/examples/main.cpp#L33).
- [x] 5. Присутствует избыточные комментарии.
[здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/sources/client.cpp#L77), [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/sources/client.cpp#L79) и [здесь](https://github.com/Niyaz97/TwitterClient/blob/d2fa582b2893203e60374c1b8bc499d9d749834e/sources/client.cpp#L166).

**Comment by rusdevops** [comment]
```
if (cin >> n) { 
  ... 
} 
else throw bad_argument(“...")  

<=>   

cin >> n; 
if (!cin) throw bad_argument(“...”); 
...
```

**Comment by Niyaz97** [comment]
corrected in [this](https://github.com/Niyaz97/TwitterClient/commit/48729d66a5ffd44d6ea9a114513d9c599141c747#diff-bfebe34154a0dfd9fc7b447fc9ed74e9) commit
